### ISSUE TITLE
Wrong Hyperlinking in the website

### ISSUE THREAD

**Issue by IamManchanda** [CloudCannon/bakery-store#1]
Dear sir, 

In the below page, 
http://jekyll.tips/jekyll-casts/seo-in-jekyll/

There is wrong hyperlinking for the text " Search Engine Optimization Starter Guide " 

It should be linked to 
`http://static.googleusercontent.com/media/www.google.com/en/us/webmasters/docs/search-engine-optimization-starter-guide.pdf`
but instead is linked to 
`http://static.googleusercontent.com/media/www.google.com/en/us/webmasters/docs/search-engine-optimization-starter-guide.pd`

**Comment by mneumegen** [comment]
Thanks for letting me know. I'll get that fixed up now.

**Comment by IamManchanda** [comment]
Welcome @mneumegen
