### ISSUE TITLE
How do i add a site.baseurl in the hyperlinking for search section

### ISSUE THREAD

**Issue by IamManchanda** [CloudCannon/bakery-store#2]
In the lunrjs tutorial ( [Episode #20](http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/) ), 

i am unable to use {{ site.baseurl }} for the links within the search results as its a js file and not html .
Just wanna know, is there any way to do the same ?

Special note: I am trying to implement the same on the creative bootstrap project. ( [Episode #29](http://jekyll.tips/jekyll-casts/converting-a-static-site-to-jekyll/) ) 
Here is my code and issue --> ~~[Line no 10](https://github.com/IamManchanda/creative-bootstrap/blob/gh-pages/js/search.js#L10)~~ [Line no 10](https://github.com/IamManchanda/creative-bootstrap/blob/1.0.0-alpha.4/js/search.js#L10) 

As i cant add {{ site.baseurl }} in the js file, so how do i implement it

**Comment by mneumegen** [comment]
Hi @IamManchanda ,

If you add empty front matter to the top of the file like this:

```
---
---
```

You can use liquid variables inside your JS file

**Comment by IamManchanda** [comment]
Thanks a lot buddy .. it worked !

Thanks for quick help @mneumegen 
Closing the issue now.
