### ISSUE TITLE
Issue with displaying for loop variables

### ISSUE THREAD

**Issue by ghost** [CloudCannon/bakery-store#5]
The varible `cupcakes` which stores 3 items does not get rendered and during running Jekyll it throws an error saying 

> found character that cannot start any token while scanning for the next token

The line number for the above error is the line which contains the first `<li>` item i.e. `-chocolate`.  
I have indented the code properly, and even tried copy pasting your code but the error was still there.

The rest of the code however works properly and the heading also gets rendered.  

P.S. Your tutorial used Jekyll version 3.1.3 but I am using Jekyll version 3.8.5 (on Mac OS X). Could this be a version issue?

**Comment by bglw** [comment]
👋 Apologies for this issue being lost — we do have a [range of new templates now](https://cloudcannon.com/community/themes/) that may be more customizable for your needs.
